/**
 * AUTO-GENERATED by scripts/generate-vo.ts — do not edit by hand.
 * Measured durations (ms) of the baked VO mp3s, merged into VOICE_CLIPS so
 * the typewriter/pacing can reference a real length before audio decodes.
 */
export const VOICE_DURATIONS: Record<string, number> = {
  "intro_01": 4023,
  "intro_02": 8908,
  "lab_narr_01": 13192,
  "lab_narr_02": 7053,
  "lab_a_01": 679,
  "lab_a_02": 967,
  "lab_a_03": 7105,
  "lab_a_04": 1280,
  "lab_a_05": 4493,
  "lab_a_06": 784,
  "lab_a_07": 1149,
  "lab_narr_03": 7784,
  "lab_b_01": 679,
  "lab_b_02": 1202,
  "lab_b_03": 2038,
  "lab_narr_04": 9038,
  "lab_c_01": 914,
  "lab_c_02": 1332,
  "lab_c_03": 601,
  "lab_narr_05": 10684,
  "lab_c_04": 549,
  "lab_c_05": 1437,
  "lab_narr_06": 10527,
  // Prologue VO imported from the uploaded assets pack (Godot jack_*/sarah_*).
  // These are the per-line hint durations from lab_builder.gd (ms) used only as
  // a pacing fallback — the real clip length is read from the audio at runtime.
  "jack_journal_entry_zero": 13500,
  "jack_get_coffee": 4000,
  "jack_to_sarah": 2000,
  "jack_no_response": 5500,
  "jack_badge_found": 5000,
  "sarah_dont_have_to": 2000,
  "jack_i_did_it_anyway": 1800,
  "sarah_look_at_readings": 2200,
  "jack_should_i_call": 1500,
  "sarah_im_the_someone": 2000,
  "jack_how_bad": 1000,
  "sarah_dont_know_yet": 1800,
  "jack_what_happened": 2000,
  "sarah_cascade_failing": 2800,
  "sarah_find_flashlight": 2600
};
