/**
 * Dev-time voice-over baker. Reads the VOICE_CLIP_LIST manifest (the single
 * source of truth for line text + casting) and synthesizes one mp3 per clip via
 * ElevenLabs, writing them to public/assets/audio/vo/<id>.mp3. Measures each
 * file with ffprobe and writes src/data/voiceDurations.ts so runtime pacing has
 * real durations. Nothing here runs at app runtime — audio is fully pre-baked.
 *
 * Run from the artifact dir:  pnpm exec tsx scripts/generate-vo.ts
 * Requires the ElevenLab_API secret in the environment (never printed).
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { VOICE_CLIP_LIST, type VoiceClip } from "../src/data/voiceClips";

const API_KEY = process.env.ElevenLab_API ?? "";
if (!API_KEY) {
  console.error("Missing ElevenLab_API secret in environment.");
  process.exit(1);
}

// `--force` re-bakes every clip; default skips clips whose mp3 already exists.
const FORCE = process.argv.includes("--force");

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const outDir = join(root, "public", "assets", "audio", "vo");
mkdirSync(outDir, { recursive: true });

const MODEL = "eleven_multilingual_v2";
const FORMAT = "mp3_44100_128";

async function synth(clip: VoiceClip, file: string): Promise<void> {
  const url = `https://api.elevenlabs.io/v1/text-to-speech/${clip.voiceId}?output_format=${FORMAT}`;
  const res = await fetch(url, {
    method: "POST",
    headers: {
      "xi-api-key": API_KEY,
      "Content-Type": "application/json",
      Accept: "audio/mpeg",
    },
    body: JSON.stringify({
      text: clip.text,
      model_id: MODEL,
      voice_settings: { stability: 0.5, similarity_boost: 0.75 },
    }),
  });
  if (!res.ok) {
    const detail = await res.text().catch(() => "");
    throw new Error(`TTS ${clip.id} → ${res.status} ${detail.slice(0, 300)}`);
  }
  writeFileSync(file, Buffer.from(await res.arrayBuffer()));
}

function durationMs(file: string): number {
  const out = execFileSync("ffprobe", [
    "-v",
    "error",
    "-show_entries",
    "format=duration",
    "-of",
    "default=nw=1:nk=1",
    file,
  ]).toString().trim();
  return Math.round(parseFloat(out) * 1000);
}

const durations: Record<string, number> = {};
for (const clip of VOICE_CLIP_LIST) {
  const file = join(outDir, `${clip.id}.mp3`);
  if (!FORCE && existsSync(file)) {
    durations[clip.id] = durationMs(file);
    console.log(`skip ${clip.id} (exists) ${durations[clip.id]}ms`);
    continue;
  }
  process.stdout.write(`synth ${clip.id} (${clip.speaker})... `);
  await synth(clip, file);
  durations[clip.id] = durationMs(file);
  console.log(`${durations[clip.id]}ms`);
}

const dest = join(root, "src", "data", "voiceDurations.ts");
const body =
  `/**\n` +
  ` * AUTO-GENERATED by scripts/generate-vo.ts — do not edit by hand.\n` +
  ` * Measured durations (ms) of the baked VO mp3s, merged into VOICE_CLIPS so\n` +
  ` * the typewriter/pacing can reference a real length before audio decodes.\n` +
  ` */\n` +
  `export const VOICE_DURATIONS: Record<string, number> = ${JSON.stringify(durations, null, 2)};\n`;
writeFileSync(dest, body);
console.log(`\nBaked ${Object.keys(durations).length} clips → ${outDir}`);
console.log(`Wrote ${dest}`);
